# Generated by Django 4.1.7 on 2023-03-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='names',
            new_name='name',
        ),
    ]
