# Generated by Django 4.1.7 on 2023-03-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_names_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='named',
        ),
    ]
