# Generated by Django 4.1.7 on 2023-03-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_name_order_named'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='named',
            new_name='name',
        ),
    ]
